#!/usr/bin/env python

import sys, os, time

sp_sc_binary = '/usr/bin/sp-sc'
vlc_binary = '/usr/bin/vlc'

def connect_to(translation):
	sp_open_connection = sp_sc_binary + " " + translation + " 3908 8908 > /dev/null &"
	os.system(sp_open_connection)
	time.sleep(5)
	vlc_open_translation = vlc_binary + " -q http://localhost:8908/tv.asf"
	os.system(vlc_open_translation)

def exit_gracefully():
	os.system("killall -9 " + sp_sc_binary)

if(len(sys.argv) == 2):
	connect_to(sys.argv[1])
else:
	print("Usage:\n")
	print("sopcast sop://broker.sopcast.com:3912/6001")

if __name__ == '__main__':
    try:
    	1 == 1
    except KeyboardInterrupt:
        pass
    finally:
        exit_gracefully()